

corr SINISTRA_M
DESTRA_a
destra_1
sinistra_1
with
SINISTRA_ar
DESTRA_ar
destra_1r
sinistra_1r.


DATASET ACTIVATE InsiemeDati1.
T-TEST PAIRS=sdo WITH r_sdo (PAIRED)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.


T-TEST PAIRS=sdo WITH r_sdo (PAIRED)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.




T-TEST PAIRS=sinistra_a WITH SINISTRA_Ar (PAIRED)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.


T-TEST PAIRS=destra_A WITH destra_Ar (PAIRED)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.

T-TEST PAIRS=destra_1 WITH destra_1r (PAIRED)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.


T-TEST PAIRS=sinistra_1 WITH sinistra_1r (PAIRED)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.



T-TEST PAIRS=DESTRA_A destra_1 WITH DESTRA_Ar destra_1r (PAIRED)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.

CORRELATIONS
  /VARIABLES=SINISTRA_A DESTRA_A destra_1 sinistra_1 with SINISTRA_Ar DESTRA_Ar destra_1r sinistra_1r
  /PRINT=TWOTAIL NOSIG  /MISSING=PAIRWISE.



T-TEST GROUPS=sex(1 2)
  /MISSING=ANALYSIS
  /VARIABLES=sdo
  /CRITERIA=CI(.95).




T-TEST GROUPS=sin_des(0 1)
  /MISSING=ANALYSIS
  /VARIABLES=bcc_tot
  /CRITERIA=CI(.95).


T-TEST GROUPS=sin_des(0 1)
  /MISSING=ANALYSIS
  /VARIABLES=estbf
gradbf
coscbf
neurobf
aperbf
  /CRITERIA=CI(.95).


